language: cpp

matrix:
  include:
  - os: windows
  - os: linux
    dist: xenial
    compiler: gcc
  - os: linux
    dist: xenial
    compiler: clang

before_script:
- mkdir _build
- cd _build
- cmake ..

script:
- cmake --build .
